A = open("34-44/40/A.txt", "r")
B = open("34-44/40/B.txt", "r")
C = open("34-44/40/C.txt", "w+")
a_text = A.read()
b_text = B.read()
C.write(a_text)
C.write(" ")
C.write(b_text)
A.close()
B.close()
C.close()